source_editor:
    tabs: 4
    show_gutter: true
_enabled_editors:
    - content
    - data
_inputs:
    title:
        type: text
    meta_tag_robots_no_index:
        type: switch
        comment: Allow robots crawlers to index page
    meta_tags:
        type: text
        comment: Meta tags splited by comma... Example, Edge, Function
    og_image:
        type: image
        comment: Open Graph Image, Social sharing image
        options:
            uploads_dir: /assets/docs/images/uploads
    description:
        type: text
        comment: Description focused to help SEO on meta description
    namespace:
        type: text
        comment: Variable used to automatic translation. To the same posts in a differente language, the value should be the same on all languages
    menu_namespace:
        type: text
        comment: Variable used to automatic include left menu.
    icon:
        type: image
        options:
            uploads_dir: /assets/docs/images/uploads
    link:
        type: url
    cards[*].title:
        comment: Card title
    cards[*].description:
        comment: Description card. Try explain in a tweet.
    cards[*].link:
        comment: Description card. Try explain in a tweet.
    cards:
        type: array
        comment: List of cards
        options:
            structures: _structures.components
            preview:
                image:
                    - key: icon
                text:
                    - key: title
                    - key: description
                    - key: link
    product_cards[*].title:
        comment: Cards section title
    product_cards:
        type: array
        comment: Content list of cards
        options:
            structures: _structures.components
            preview:
                text:
                    - key: title
                array:
                    - key: cards
    permalink:
        type: text
        comment: "English URL of cases post. If not to publish, remove the default value. Example: /documentation/my-post/"
        options:
            empty_type: string

collections_config:
    homes_en:
        path: './src/content/docs/en/homes'
        schemas:
            default:
                path: schemas/homes.md
        create:
            path: '{filename}.mdx'
    homes_ptbr:
        path: './src/content/docs/pt-br/homes'
        schemas:
            default:
                path: schemas/homes.md
        create:
            path: '{filename}.mdx'
    pages_en:
        path: './src/content/docs/en/pages'
        schemas:
            default:
                path: schemas/doc.md
        create:
            path: '{filename}.mdx'
    pages_ptbr:
        path: './src/content/docs/pt-br/pages'
        schemas:
            default:
                path: schemas/doc.md
        create:
            path: '{filename}.mdx'
    
